### ISSUE TITLE
Add link to the repo in the README

### ISSUE THREAD

**Issue by jecisc** [pharo-project/pharo-beacon#3]
I typed "Beacon Pharo" in google and the github project was the first link but it does not say where are the sources.

**Comment by noha** [comment]
The sources are in smalltalkhub. Beacon should be integrated in pharo so we left the source in smalltalkhub in order not to complicate things. I plan to move the sources to github soon.

Norbert

**Comment by noha** [comment]
Beacon is now migrated to here
