### ISSUE TITLE
New stable version should be released

### ISSUE THREAD

**Issue by jecisc** [pharo-project/pharo-beacon#4]
I wanted to try Beacon so I installed it on a Pharo 4 image. I wanted to try the StringSignal but first thing I got was a deprcation. 

I think a new stable version should be released since this is corrected in the dev version.

**Comment by philippeback** [comment]
Because you need to use emit: now and not log:

Phil

**Comment by jecisc** [comment]
I don't have emit: in the stable version.

**Comment by philippeback** [comment]
Check what is in Moose6.1 and use that.

Phil

**Comment by jecisc** [comment]
It is probably the dev version. But we have too much dependencies at Synectique. If we takes the dev version of all of them, everything will break all the time. So we need a stable version.

**Comment by noha** [comment]
I assume this is done
